update_properties: lower risk of generating empty files if the update fail

diff --git a/scripts/update_properties b/scripts/update_properties
--- a/scripts/update_properties
+++ b/scripts/update_properties
@@ -1,16 +1,20 @@
 #!/usr/bin/env bash
-
 set -eu
 
-wd sparql ./scripts/assets/properties.rq --index property > ./scripts/assets/properties.json
+wd sparql ./scripts/assets/properties.rq --index property > ./scripts/assets/properties.json.tmp
 
 # Using printf to avoid getting an undesired newline break
-printf "// Generated by scripts/update_properties\nmodule.exports = " > ./lib/properties.js
-./scripts/get_properties_index >> ./lib/properties.js
+printf "// Generated by scripts/update_properties\nmodule.exports = " > ./lib/properties.js.tmp
+./scripts/get_properties_index >> ./lib/properties.js.tmp
 
 # If standard is installed, fix possible indentation inconsistencies
 # to avoid having standard report them later
-standard --fix ./lib/properties.js || echo 'not linting'
+standard --fix ./lib/properties.js.tmp || echo 'not linting'
+
+# Now that risky operations are over, we can cleanup
+# with a low risk of crashing and letting empty files behind us
+mv ./scripts/assets/properties.json.tmp ./scripts/assets/properties.json
+mv ./lib/properties.js.tmp ./lib/properties.js
 
 echo "generating properties index"
 ./scripts/generate_properties_index
